import { Note, Task, ChatMessage, UserProfile, NotificationItem } from '../types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Tanmoy',
  email: 'tanmoy@lifeflow.ai',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  streakDays: 7,
  totalCompletedTasks: 42,
  aiRequestsUsed: 89,
  themeMode: 'light',
  hasOnboarded: false, // will show onboarding on first load or can skip
  notificationsEnabled: true,
  reminderSound: true,
  hapticsEnabled: true,
};

const getTodayString = (offsetDays = 0): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    title: 'Review Q4 Product Roadmap & Goals',
    description: 'Finalize core AI feature specs, milestone timelines, and sync with engineering team.',
    dueDate: getTodayString(0),
    dueTime: '09:30 AM',
    priority: 'high',
    category: 'Work',
    completed: true,
    reminder: '15m before',
    repeat: 'none',
    scheduledTimeBlock: 'morning',
    estimatedMinutes: 45,
    subtasks: [
      { id: 'st-1', title: 'Check analytics dashboard', completed: true },
      { id: 'st-2', title: 'Highlight top 3 blockers', completed: true },
      { id: 'st-3', title: 'Send briefing doc to team', completed: true },
    ],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 't-2',
    title: 'Complete Mobile App Design Polish',
    description: 'Refine typography, card micro-interactions, dark mode tokens, and icon alignments.',
    dueDate: getTodayString(0),
    dueTime: '11:00 AM',
    priority: 'high',
    category: 'Work',
    completed: true,
    reminder: 'At time',
    repeat: 'none',
    scheduledTimeBlock: 'morning',
    estimatedMinutes: 60,
    subtasks: [
      { id: 'st-4', title: 'Update color system variables', completed: true },
      { id: 'st-5', title: 'Test touch target bounds on small screens', completed: true },
      { id: 'st-6', title: 'Export clean asset sheets', completed: true },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    completedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 't-3',
    title: '30-minute Cardio & Stretching',
    description: 'Mid-day refresh: 20 min brisk run + 10 min core stretching routine.',
    dueDate: getTodayString(0),
    dueTime: '01:00 PM',
    priority: 'medium',
    category: 'Health',
    completed: true,
    reminder: '15m before',
    repeat: 'daily',
    scheduledTimeBlock: 'afternoon',
    estimatedMinutes: 30,
    subtasks: [],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    completedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 't-4',
    title: 'Prepare AI Strategy Presentation',
    description: 'Structure 10-slide deck on AI productivity pipelines and schedule optimization algorithms.',
    dueDate: getTodayString(0),
    dueTime: '03:30 PM',
    priority: 'high',
    category: 'Work',
    completed: false,
    reminder: '1 hour before',
    repeat: 'none',
    scheduledTimeBlock: 'afternoon',
    estimatedMinutes: 90,
    subtasks: [
      { id: 'st-7', title: 'Outline value proposition', completed: true },
      { id: 'st-8', title: 'Add user benchmark metrics', completed: false },
      { id: 'st-9', title: 'Draft closing summary & Q&A notes', completed: false },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 't-5',
    title: 'Research TypeScript & Reanimated Patterns',
    description: 'Deep dive into performant list transitions and gesture handling best practices.',
    dueDate: getTodayString(0),
    dueTime: '05:15 PM',
    priority: 'medium',
    category: 'Study',
    completed: false,
    reminder: 'none',
    repeat: 'none',
    scheduledTimeBlock: 'afternoon',
    estimatedMinutes: 45,
    subtasks: [
      { id: 'st-10', title: 'Read Expo 52 release notes', completed: true },
      { id: 'st-11', title: 'Benchmark smooth tab transitions', completed: false },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 't-6',
    title: 'Weekly Grocery & Meal Prep List',
    description: 'Stock up on fresh greens, almond milk, berries, and organic protein for the week.',
    dueDate: getTodayString(0),
    dueTime: '06:45 PM',
    priority: 'low',
    category: 'Personal',
    completed: false,
    reminder: 'At time',
    repeat: 'weekly',
    scheduledTimeBlock: 'evening',
    estimatedMinutes: 30,
    subtasks: [
      { id: 'st-12', title: 'Fresh produce & spinach', completed: false },
      { id: 'st-13', title: 'Greek yogurt & oats', completed: false },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 't-7',
    title: 'Read 2 Chapters of "Atomic Habits"',
    description: 'Evening wind-down reading: habit stacking and friction reduction methods.',
    dueDate: getTodayString(0),
    dueTime: '09:00 PM',
    priority: 'low',
    category: 'Ideas',
    completed: false,
    reminder: '15m before',
    repeat: 'daily',
    scheduledTimeBlock: 'evening',
    estimatedMinutes: 30,
    subtasks: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 't-8',
    title: 'Review Investment Portfolio & Budget',
    description: 'Check monthly savings target, rebalance index funds, and log recurring subscriptions.',
    dueDate: getTodayString(1),
    dueTime: '10:00 AM',
    priority: 'medium',
    category: 'Finance',
    completed: false,
    reminder: '1 day before',
    repeat: 'monthly',
    scheduledTimeBlock: 'morning',
    estimatedMinutes: 40,
    subtasks: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 't-9',
    title: 'Design System Documentation Sync',
    description: 'Consolidate token definitions for typography, elevation, spacing and accessibility colors.',
    dueDate: getTodayString(2),
    dueTime: '02:00 PM',
    priority: 'high',
    category: 'Work',
    completed: false,
    reminder: '1 hour before',
    repeat: 'none',
    scheduledTimeBlock: 'afternoon',
    estimatedMinutes: 60,
    subtasks: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'n-1',
    title: '🚀 LifeFlow AI Architecture & Product Vision',
    content: `## Vision\nLifeFlow AI combines intuitive task management with proactive ambient intelligence.\n\n### Key Pillars:\n- **Instant Frictionless Capture**: Floating actions, quick voice notes, smart text parser.\n- **AI Daily Planner**: Smart energy-based schedule slotting.\n- **Actionable Notes**: Convert any note section directly into scheduled tasks.\n- **Zero Clutter**: Clean minimalist typography, comfortable 8px grid system.`,
    category: 'Work',
    tags: ['Vision', 'DesignSystem', 'AI'],
    pinned: true,
    favorite: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    summary: 'Core vision combining intuitive tasks with ambient AI scheduling and frictionless note-to-task conversion.',
  },
  {
    id: 'n-2',
    title: '💡 Breakthrough Startup Ideas for 2025',
    content: `1. **Ambient AI Meeting Scribe**: Real-time action item extractor with autonomous calendar scheduling.\n2. **Micro-Habit AI Coach**: Tracks behavioral friction and suggests 2-minute micro-steps.\n3. **Visual Knowledge Canvas**: Infinite spatial canvas for connecting ideas, tasks, and markdown docs seamlessly.\n\n*Next step: Validate AI meeting scribe prototype with 5 beta users.*`,
    category: 'Ideas',
    tags: ['Brainstorm', 'Startup', 'Innovation'],
    pinned: true,
    favorite: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    summary: 'Three high-impact startup concepts centering around ambient meeting agents and habit friction reduction.',
  },
  {
    id: 'n-3',
    title: '📚 Machine Learning & LLM Agent Concepts',
    content: `### Core Notes from ML Research:\n- **Context Window Management**: Efficient sliding summaries minimize latency and tokens.\n- **Structured Tool Calling**: Returning deterministic JSON schemas for task creation.\n- **Retrieval Augmented Generation (RAG)**: Indexing personal notes locally enables semantic search across months of notes.\n\n> "The most powerful tools don't replace thought; they eliminate the friction of execution."`,
    category: 'Study',
    tags: ['AI', 'Tech', 'Research'],
    pinned: false,
    favorite: true,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    summary: 'Key ML engineering takeaways on structured schema tool calling and local vector retrieval.',
  },
  {
    id: 'n-4',
    title: '🌱 Personal Growth & Mindfulness Routine',
    content: `### Daily Rhythm:\n- **Morning (7:00 AM)**: 10 minutes breathwork, sunlight exposure, hydration.\n- **Midday**: Step away from screen during lunch, take a brisk 15-minute walk.\n- **Evening**: No screens 45 minutes before sleep, jot down top 3 wins of the day.\n\n*Affirmation*: "Consistency is what transforms average into excellence."`,
    category: 'Personal',
    tags: ['Mindfulness', 'Habits', 'Wellness'],
    pinned: false,
    favorite: false,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    summary: 'Structured daily rhythm focusing on breathwork, midday walk breaks, and screen-free evening wind down.',
  },
  {
    id: 'n-5',
    title: '⚡ UI/UX Micro-Interactions Checklist',
    content: `Checklist for world-class mobile polish:\n- [x] Smooth checkbox strike-through animation\n- [x] Spring animations on floating action button\n- [ ] Subtle haptic feedback on task completion\n- [x] Consistent 8px spacing rhythm\n- [x] High contrast accessible text in dark mode`,
    category: 'Important',
    tags: ['Design', 'Mobile', 'Polish'],
    pinned: false,
    favorite: false,
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    summary: 'Checklist of mobile micro-interactions to guarantee premium feel and accessibility.',
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'c-1',
    sender: 'ai',
    text: "👋 Hi Tanmoy! I'm **LifeFlow AI**, your personal productivity partner.\n\nI can help you plan your schedule, summarize notes, extract tasks from thoughts, prioritize your to-do list, or answer anything about your workspace.\n\nHow can I empower your day today?",
    timestamp: '09:00 AM',
  },
  {
    id: 'c-2',
    sender: 'user',
    text: 'Can you summarize my schedule and tell me what to focus on this afternoon?',
    timestamp: '09:02 AM',
  },
  {
    id: 'c-3',
    sender: 'ai',
    text: "✨ Great job completing your **2 morning tasks**! Here is your afternoon gameplan:\n\n1. 🎯 **Highest Priority**: `Prepare AI Strategy Presentation` (due 3:30 PM, ~90 min focus block).\n2. 📖 **Secondary Priority**: `Research TypeScript & Reanimated Patterns` (due 5:15 PM).\n3. 💡 **Pro-Tip**: Take a short 5-minute breather before starting your presentation deck to maximize deep focus.\n\nWould you like me to generate a 10-slide outline for your presentation?",
    timestamp: '09:03 AM',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '🔥 7-Day Streak Achieved!',
    message: 'Awesome consistency! You completed all scheduled priorities for 7 days in a row.',
    time: '25m ago',
    read: false,
    type: 'streak',
  },
  {
    id: 'notif-2',
    title: '⏰ Upcoming Deadline',
    message: '"Prepare AI Strategy Presentation" is scheduled for 3:30 PM.',
    time: '1h ago',
    read: false,
    type: 'reminder',
  },
  {
    id: 'notif-3',
    title: '✨ AI Schedule Optimized',
    message: 'LifeFlow AI arranged your afternoon tasks for peak energy focus.',
    time: '3h ago',
    read: true,
    type: 'ai',
  },
];
